class HttpResponse {
  static const HTTP_CONTINUE = 100;
  static const HTTP_SWITCHING_PROTOCOLS = 101;
  static const HTTP_PROCESSING = 102; // RFC2518
  static const HTTP_EARLY_HINTS = 103; // RFC8297
  static const HTTP_OK = 200;
  static const HTTP_CREATED = 201;
  static const HTTP_ACCEPTED = 202;
  static const HTTP_NON_AUTHORITATIVE_INFORMATION = 203;
  static const HTTP_NO_CONTENT = 204;
  static const HTTP_RESET_CONTENT = 205;
  static const HTTP_PARTIAL_CONTENT = 206;
  static const HTTP_MULTI_STATUS = 207; // RFC4918
  static const HTTP_ALREADY_REPORTED = 208; // RFC5842
  static const HTTP_IM_USED = 226; // RFC3229
  static const HTTP_MULTIPLE_CHOICES = 300;
  static const HTTP_MOVED_PERMANENTLY = 301;
  static const HTTP_FOUND = 302;
  static const HTTP_SEE_OTHER = 303;
  static const HTTP_NOT_MODIFIED = 304;
  static const HTTP_USE_PROXY = 305;
  static const HTTP_RESERVED = 306;
  static const HTTP_TEMPORARY_REDIRECT = 307;
  static const HTTP_PERMANENTLY_REDIRECT = 308; // RFC7238
  static const HTTP_BAD_REQUEST = 400;
  static const HTTP_UNAUTHORIZED = 401;
  static const HTTP_PAYMENT_REQUIRED = 402;
  static const HTTP_FORBIDDEN = 403;
  static const HTTP_NOT_FOUND = 404;
  static const HTTP_METHOD_NOT_ALLOWED = 405;
  static const HTTP_NOT_ACCEPTABLE = 406;
  static const HTTP_PROXY_AUTHENTICATION_REQUIRED = 407;
  static const HTTP_REQUEST_TIMEOUT = 408;
  static const HTTP_CONFLICT = 409;
  static const HTTP_GONE = 410;
  static const HTTP_LENGTH_REQUIRED = 411;
  static const HTTP_PRECONDITION_FAILED = 412;
  static const HTTP_REQUEST_ENTITY_TOO_LARGE = 413;
  static const HTTP_REQUEST_URI_TOO_LONG = 414;
  static const HTTP_UNSUPPORTED_MEDIA_TYPE = 415;
  static const HTTP_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
  static const HTTP_EXPECTATION_FAILED = 417;
  static const HTTP_I_AM_A_TEAPOT = 418; // RFC2324
  static const HTTP_MISDIRECTED_REQUEST = 421; // RFC7540
  static const HTTP_UNPROCESSABLE_ENTITY = 422; // RFC4918
  static const HTTP_LOCKED = 423; // RFC4918
  static const HTTP_FAILED_DEPENDENCY = 424; // RFC4918
  static const HTTP_TOO_EARLY = 425; // RFC-ietf-httpbis-replay-04
  static const HTTP_UPGRADE_REQUIRED = 426; // RFC2817
  static const HTTP_PRECONDITION_REQUIRED = 428; // RFC6585
  static const HTTP_TOO_MANY_REQUESTS = 429; // RFC6585
  static const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = 431; // RFC6585
  static const HTTP_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
  static const HTTP_INTERNAL_SERVER_ERROR = 500;
  static const HTTP_NOT_IMPLEMENTED = 501;
  static const HTTP_BAD_GATEWAY = 502;
  static const HTTP_SERVICE_UNAVAILABLE = 503;
  static const HTTP_GATEWAY_TIMEOUT = 504;
  static const HTTP_VERSION_NOT_SUPPORTED = 505;
  static const HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL = 506; // RFC2295
  static const HTTP_INSUFFICIENT_STORAGE = 507; // RFC4918
  static const HTTP_LOOP_DETECTED = 508; // RFC5842
  static const HTTP_NOT_EXTENDED = 510; // RFC2774
  static const HTTP_NETWORK_AUTHENTICATION_REQUIRED = 511; // RFC6585
}
